[package]
name = "rober/roviz"
description = "Roviz is an open-source Roblox library used to debug in a visualizing manner."
version = "0.0.1"
license = "MIT"
authors = ["Robert Zak <roberthelgi@icloud.com>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Trove = "sleitnick/trove@0.5.0"
